### ISSUE TITLE
Doesn't work on 3.2?

### ISSUE THREAD

**Issue by Blake-** [dartmouth-dltg/container_management_labels#10]
Fails with this error on 3.2

```
I, [2022-07-25T14:52:46.297555 #21339]  INFO -- : Completed 500 Internal Server Error in 840ms
F, [2022-07-25T14:52:46.300954 #21339] FATAL -- :   
F, [2022-07-25T14:52:46.301160 #21339] FATAL -- : ActionView::Template::Error (undefined method `to_a' for #<ActionController::Parameters:0x26be973b>
Did you mean?  to_s
               to_h):
F, [2022-07-25T14:52:46.301912 #21339] FATAL -- :     15:         fields = AppConfig[:container_management_labels].map{|h| h.keys}.flatten
    16:         
    17:         # make sure the params are ordered the same as the fields set in the config
    18:         params_new = Hash[params.to_a.sort_by{|param| fields.index(param)}]
    19:       %>
    20:   
    21:       <% labels.each do |label| %>
F, [2022-07-25T14:52:46.302198 #21339] FATAL -- :   
F, [2022-07-25T14:52:46.302330 #21339] FATAL -- : app/helpers/application_helper.rb:311:in `render_aspace_partial'
app/controllers/application_controller.rb:797:in `set_locale'
```

**Comment by jdshaw** [comment]
Looks like you are running from the main branch? If so, please try it with the 3.0.0 branch (as-300)

Because this plugin is overriding some views and bridges the 2.8.0->2.8.1 Rails update, there are specific branches for specific ArchivesSpace releases (hopefully labelled somewhat clearly) that will work with that AS release up to the next AS release name. To clarify (I hope!)

Main is currently for versions 2.7.1 (and may work with 2.7.0). 
The 2.8.0 branch is for 2.8.0 only
The 2.8.1 branch is for 2.8.1 only
The 3.0.0 branch should work for versions from 3.0.0 to 3.2.0

Please give a shout if the 3.0.0 branch is still failing for you in AS v3.2.0

I need to make that clearer in the ReadMe!

**Comment by Blake-** [comment]
Ah, ok, will do, thanks!!

**Comment by Blake-** [comment]
Looks like that did the trick, no error when I'm on the right branch.
